import { Product, Review, User, Order } from "./types";

export const products: Product[] = [
  // Bicycles
  {
    id: "bike-1",
    name: "Mountain Pro X1",
    description: "Professional mountain bike with carbon frame and advanced suspension system. Perfect for challenging terrains and extreme trails.",
    price: 2499.99,
    originalPrice: 2999.99,
    category: "bicycle",
    subCategory: "Mountain",
    brand: "ProCycle",
    images: [
      "https://images.unsplash.com/photo-1576435728678-68d0fbf94e91?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1511994298241-608e28f14fde?w=800&h=600&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 124,
    stock: 15,
    featured: true,
    specifications: {
      "Frame Material": "Carbon Fiber",
      "Wheel Size": "29 inches",
      "Gears": "21-speed",
      "Suspension": "Full Suspension",
      "Weight": "12.5 kg",
    },
  },
  {
    id: "bike-2",
    name: "City Cruiser Elite",
    description: "Elegant city bike designed for comfortable urban commuting. Features ergonomic design and smooth riding experience.",
    price: 899.99,
    category: "bicycle",
    subCategory: "City",
    brand: "UrbanRide",
    images: [
      "https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1532298229144-0ec0c57515c7?w=800&h=600&fit=crop",
    ],
    rating: 4.5,
    reviewCount: 89,
    stock: 25,
    featured: true,
    specifications: {
      "Frame Material": "Aluminum Alloy",
      "Wheel Size": "26 inches",
      "Gears": "7-speed",
      "Weight": "14 kg",
    },
  },
  {
    id: "bike-3",
    name: "Road Racer 3000",
    description: "High-performance road bike built for speed and endurance. Lightweight frame with aerodynamic design.",
    price: 1899.99,
    originalPrice: 2199.99,
    category: "bicycle",
    subCategory: "Road",
    brand: "SpeedMaster",
    images: [
      "https://images.unsplash.com/photo-1507035895480-2b3156c31fc8?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1571333250630-f0230c320b6d?w=800&h=600&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 156,
    stock: 12,
    featured: true,
    specifications: {
      "Frame Material": "Carbon Fiber",
      "Wheel Size": "28 inches",
      "Gears": "18-speed",
      "Weight": "8.5 kg",
    },
  },
  {
    id: "bike-4",
    name: "Electric Commuter Pro",
    description: "Premium electric bike with long-range battery and smart features. Perfect for daily commuting.",
    price: 3299.99,
    category: "bicycle",
    subCategory: "Electric",
    brand: "E-Motion",
    images: [
      "https://images.unsplash.com/photo-1559348349-86f1f65817fe?w=800&h=600&fit=crop",
      "https://images.unsplash.com/photo-1571068316344-75bc76f77890?w=800&h=600&fit=crop",
    ],
    rating: 4.7,
    reviewCount: 203,
    stock: 8,
    featured: true,
    specifications: {
      "Frame Material": "Aluminum Alloy",
      "Wheel Size": "27.5 inches",
      "Motor": "250W",
      "Battery": "48V 15Ah",
      "Range": "80 km",
      "Weight": "22 kg",
    },
  },
  {
    id: "bike-5",
    name: "Kids Adventure 20",
    description: "Safe and fun bicycle for young riders. Durable construction with safety features.",
    price: 349.99,
    category: "bicycle",
    subCategory: "Kids",
    brand: "JuniorRide",
    images: [
      "https://images.unsplash.com/photo-1519583272095-6433daf26b6e?w=800&h=600&fit=crop",
    ],
    rating: 4.6,
    reviewCount: 67,
    stock: 30,
    specifications: {
      "Frame Material": "Steel",
      "Wheel Size": "20 inches",
      "Gears": "Single Speed",
      "Weight": "10 kg",
    },
  },
  {
    id: "bike-6",
    name: "BMX Stunt Master",
    description: "Professional BMX bike for tricks and stunts. Reinforced frame and responsive handling.",
    price: 599.99,
    category: "bicycle",
    subCategory: "BMX",
    brand: "StuntPro",
    images: [
      "https://images.unsplash.com/photo-1475666675596-cca2035b3d79?w=800&h=600&fit=crop",
    ],
    rating: 4.4,
    reviewCount: 45,
    stock: 18,
    specifications: {
      "Frame Material": "Chromoly Steel",
      "Wheel Size": "20 inches",
      "Weight": "11 kg",
    },
  },

  // Parts
  {
    id: "part-1",
    name: "Premium Carbon Fiber Helmet",
    description: "Ultra-lightweight helmet with advanced ventilation system and impact protection.",
    price: 149.99,
    originalPrice: 199.99,
    category: "parts",
    subCategory: "Safety",
    brand: "SafeRide",
    images: [
      "https://images.unsplash.com/photo-1557438159-51eec7a6c9e8?w=800&h=600&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 234,
    stock: 50,
    featured: true,
  },
  {
    id: "part-2",
    name: "Hydraulic Disc Brake Set",
    description: "High-performance hydraulic disc brakes for superior stopping power in all conditions.",
    price: 249.99,
    category: "parts",
    subCategory: "Brakes",
    brand: "BrakeMaster",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    ],
    rating: 4.9,
    reviewCount: 178,
    stock: 35,
    featured: true,
  },
  {
    id: "part-3",
    name: "LED Light Set Front & Rear",
    description: "Bright LED lights with multiple modes. USB rechargeable with long battery life.",
    price: 39.99,
    category: "parts",
    subCategory: "Lights",
    brand: "BrightPath",
    images: [
      "https://images.unsplash.com/photo-1571380401583-72ca84994796?w=800&h=600&fit=crop",
    ],
    rating: 4.6,
    reviewCount: 312,
    stock: 100,
  },
  {
    id: "part-4",
    name: "Professional Bike Pump",
    description: "High-pressure floor pump with accurate gauge. Compatible with all valve types.",
    price: 44.99,
    category: "parts",
    subCategory: "Tools",
    brand: "PumpPro",
    images: [
      "https://images.unsplash.com/photo-1609198092357-c7a0c9c6b42c?w=800&h=600&fit=crop",
    ],
    rating: 4.7,
    reviewCount: 156,
    stock: 60,
  },
  {
    id: "part-5",
    name: "Gel Padded Cycling Gloves",
    description: "Comfortable cycling gloves with gel padding and breathable fabric.",
    price: 29.99,
    category: "parts",
    subCategory: "Accessories",
    brand: "ComfortGear",
    images: [
      "https://images.unsplash.com/photo-1587033411391-5d9e51cce126?w=800&h=600&fit=crop",
    ],
    rating: 4.5,
    reviewCount: 89,
    stock: 75,
  },
  {
    id: "part-6",
    name: "Carbon Fiber Water Bottle Cage",
    description: "Lightweight and durable bottle cage. Secure grip for rough terrain.",
    price: 24.99,
    category: "parts",
    subCategory: "Accessories",
    brand: "ProCycle",
    images: [
      "https://images.unsplash.com/photo-1523293182086-7651a899d37f?w=800&h=600&fit=crop",
    ],
    rating: 4.4,
    reviewCount: 67,
    stock: 90,
  },
  {
    id: "part-7",
    name: "Multi-Tool Kit 16-in-1",
    description: "Compact multi-tool with 16 functions. Essential for on-the-go repairs.",
    price: 34.99,
    category: "parts",
    subCategory: "Tools",
    brand: "ToolMaster",
    images: [
      "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?w=800&h=600&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 201,
    stock: 55,
  },
  {
    id: "part-8",
    name: "Ergonomic Bike Saddle",
    description: "Memory foam saddle with ergonomic design for maximum comfort on long rides.",
    price: 79.99,
    originalPrice: 99.99,
    category: "parts",
    subCategory: "Comfort",
    brand: "ComfortRide",
    images: [
      "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&h=600&fit=crop",
    ],
    rating: 4.6,
    reviewCount: 143,
    stock: 40,
  },
  {
    id: "part-9",
    name: "Bike Lock Heavy Duty",
    description: "Hardened steel U-lock with anti-theft protection. Includes mounting bracket.",
    price: 54.99,
    category: "parts",
    subCategory: "Security",
    brand: "SecureLock",
    images: [
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop",
    ],
    rating: 4.7,
    reviewCount: 189,
    stock: 45,
  },
  {
    id: "part-10",
    name: "Bike Computer GPS",
    description: "Advanced GPS bike computer with navigation, performance tracking, and wireless connectivity.",
    price: 199.99,
    category: "parts",
    subCategory: "Electronics",
    brand: "TechCycle",
    images: [
      "https://images.unsplash.com/photo-1551830820-330a71b99659?w=800&h=600&fit=crop",
    ],
    rating: 4.5,
    reviewCount: 98,
    stock: 25,
  },
  {
    id: "part-11",
    name: "Clipless Pedals Pro",
    description: "Professional clipless pedals with adjustable tension and dual-sided entry.",
    price: 129.99,
    category: "parts",
    subCategory: "Pedals",
    brand: "PedalPro",
    images: [
      "https://images.unsplash.com/photo-1617043786394-f977fa12eddf?w=800&h=600&fit=crop",
    ],
    rating: 4.8,
    reviewCount: 167,
    stock: 30,
  },
  {
    id: "part-12",
    name: "Bike Chain Lubricant",
    description: "Premium chain lubricant for smooth operation and extended chain life.",
    price: 14.99,
    category: "parts",
    subCategory: "Maintenance",
    brand: "ChainCare",
    images: [
      "https://images.unsplash.com/photo-1581235720704-06d3acfcb36f?w=800&h=600&fit=crop",
    ],
    rating: 4.6,
    reviewCount: 245,
    stock: 120,
  },
];

export const reviews: Review[] = [
  {
    id: "rev-1",
    productId: "bike-1",
    userId: "user-1",
    userName: "John Smith",
    rating: 5,
    comment: "Absolutely amazing bike! The carbon frame is incredibly light and the suspension handles rough trails perfectly. Best purchase I've made this year!",
    date: "2025-09-15",
    helpful: 24,
  },
  {
    id: "rev-2",
    productId: "bike-1",
    userId: "user-2",
    userName: "Sarah Johnson",
    rating: 4,
    comment: "Great bike overall. Very responsive and handles well. Only minor issue is the seat could be more comfortable for long rides.",
    date: "2025-09-20",
    helpful: 12,
  },
  {
    id: "rev-3",
    productId: "bike-2",
    userId: "user-3",
    userName: "Mike Davis",
    rating: 5,
    comment: "Perfect for city commuting! Smooth ride and very comfortable. The design is sleek and modern.",
    date: "2025-09-18",
    helpful: 18,
  },
  {
    id: "rev-4",
    productId: "part-1",
    userId: "user-4",
    userName: "Emily Brown",
    rating: 5,
    comment: "This helmet is incredibly light and comfortable. Great ventilation too. Highly recommend!",
    date: "2025-09-22",
    helpful: 31,
  },
  {
    id: "rev-5",
    productId: "part-2",
    userId: "user-5",
    userName: "David Wilson",
    rating: 5,
    comment: "Best brakes I've ever used. Installation was straightforward and the stopping power is incredible.",
    date: "2025-09-25",
    helpful: 27,
  },
];

export const dummyUsers: User[] = [
  {
    id: "user-1",
    email: "john@example.com",
    name: "John Smith",
    role: "customer",
    addresses: [
      {
        id: "addr-1",
        name: "Home",
        street: "123 Main Street",
        city: "New York",
        state: "NY",
        zipCode: "10001",
        country: "USA",
        phone: "+1 234-567-8900",
        isDefault: true,
      },
    ],
  },
  {
    id: "admin-1",
    email: "admin@bicycleshop.com",
    name: "Admin User",
    role: "admin",
  },
];

export const dummyOrders: Order[] = [
  {
    id: "order-1",
    userId: "user-1",
    items: [
      { product: products[0], quantity: 1 },
      { product: products[6], quantity: 1 },
    ],
    total: 2649.98,
    status: "delivered",
    shippingAddress: {
      id: "addr-1",
      name: "Home",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      phone: "+1 234-567-8900",
    },
    billingAddress: {
      id: "addr-1",
      name: "Home",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      phone: "+1 234-567-8900",
    },
    paymentMethod: "Credit Card",
    date: "2025-09-01",
    trackingNumber: "TRK123456789",
  },
  {
    id: "order-2",
    userId: "user-1",
    items: [
      { product: products[8], quantity: 2 },
      { product: products[9], quantity: 1 },
    ],
    total: 309.97,
    status: "shipped",
    shippingAddress: {
      id: "addr-1",
      name: "Home",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      phone: "+1 234-567-8900",
    },
    billingAddress: {
      id: "addr-1",
      name: "Home",
      street: "123 Main Street",
      city: "New York",
      state: "NY",
      zipCode: "10001",
      country: "USA",
      phone: "+1 234-567-8900",
    },
    paymentMethod: "PayPal",
    date: "2025-09-28",
    trackingNumber: "TRK987654321",
  },
];

export const categories = {
  bicycle: ["Mountain", "City", "Road", "Electric", "Kids", "BMX"],
  parts: [
    "Safety",
    "Brakes",
    "Lights",
    "Tools",
    "Accessories",
    "Comfort",
    "Security",
    "Electronics",
    "Pedals",
    "Maintenance",
  ],
};

export const brands = [
  "ProCycle",
  "UrbanRide",
  "SpeedMaster",
  "E-Motion",
  "JuniorRide",
  "StuntPro",
  "SafeRide",
  "BrakeMaster",
  "BrightPath",
  "PumpPro",
  "ComfortGear",
  "ToolMaster",
  "ComfortRide",
  "SecureLock",
  "TechCycle",
  "PedalPro",
  "ChainCare",
];
